### ISSUE TITLE
Having trouble with ensureSignedIn

### ISSUE THREAD

**Issue by dovrosenberg** [meteor-useraccounts/flow-routing#2] opened 2015-08-09 16:46 UTC
Thanks for the all the work on this.  

I've got everything working great if I don't filter out logged out users.  All the sign-in, reset password, etc. templates get created and route correctly.  But as soon as I do:

`FlowRouter.triggers.enter([AccountsTemplates.ensureSignedIn]);`

it all stops working.

All the routes are properly redirected to sign-in, and I can see the redirect being called, but the rendering code [here] (https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/core.js#L211) never gets called, nor does the route-specific [trigger] (https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/core.js#L195)

Any ideas?

**Comment by PhilippSpo** [comment] 2015-08-09 17:01
I guess there is a infinit redirect loop happening.
I have it set up like this:
```
FlowRouter.triggers.enter([AccountsTemplates.ensureSignedIn], {
    except: [ 'signIn', 'signUp', 'forgotPwd',
        'resetPwd',
        'verifyEmail', 'resendVerificationEmail'
    ]
});
```

**Comment by jshimko** [comment] 2015-08-10 03:46
Oops.  I fixed that, but apparently never committed/pushed it.  I'm running the development version locally, so it was working fine for me.  Sorry about that guys.  

The ensureSignedIn helper now [checks][1] to make sure you're not already on an AccountsTemplates route before redirecting.

Now we just need @splendido to push that up to Atmosphere when he has a moment!   :)

[1]: https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L55

**Comment by splendido** [comment] 2015-08-10 18:10
this would mean bump all useraccounts packages to 1.12.1 :(
Do you think it's fine to do it right now?

**Comment by 100ideas** [comment] 2015-08-10 23:51
Might be the cause of this bug reported over in https://github.com/meteor-useraccounts/boilerplates/issues/13

**Comment by jshimko** [comment] 2015-08-11 05:02
The issue mentioned at https://github.com/meteor-useraccounts/boilerplates/issues/13 has been resolved (you can read the details in my comment there).

@splendido, as far as I can tell, this should be good to go now.  I've tested everything I can think of and it's all working.  Default routes, custom routes with custom options, etc.  Everything behaves as it should.  Sorry for the republish inconvenience.

**Comment by splendido** [comment] 2015-08-11 19:57
Bumping now...

**Closed** 2015-08-11 20:00 UTC
